#include <stdio.h>
#include <math.h>

/*
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

int tau(int n){
	int count = 0;
	int rootish = floor(sqrt(n));
	for (int trial = 1; trial < rootish; trial++){
		if (n % trial == 0){
			count += 2;
		}
	}
	if (rootish * rootish == n){
		count += 1;
	}
	return count;
}

int main(){
	int i = 1;
	int n = 0;
	int num_divisors = 0;
	while (num_divisors <= 500){
		n += i;
		i += 1;
		num_divisors = tau(n);
	}
	printf("%d\n", n);
	return 0;
}