#include <stdio.h>

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

unsigned sum_of_even_fibonacci_upto(unsigned max){
	unsigned next;
	unsigned previous = 1;
	unsigned current  = 2;
	unsigned sum      = 0;
	while (current < max){
		if (current % 2 == 0) {
			sum += current;
		}
		next = previous + current;
		previous = current;
		current = next;
	}
	return sum;
}

int main(){
	printf( "%u\n", sum_of_even_fibonacci_upto(4e6) );
	return 0;
}