#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include "vector.c"

/* Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D? */

size_t pentagonal(size_t n){
	//shifted so that pentagonal(0) = 1 is the first pent number
	n++;
	return n * (3 * n - 1) / 2;
}

bool is_pentagonal(size_t P){
	size_t discriminant = 1 + 24*P;
	// is P a perfect square?
	size_t candidate = 0;
	size_t square = 0;
	while (square < discriminant){
		candidate++;
		square = candidate * candidate;
	}
	// candidate is the largest integer whose square is <= discriminantadas
	return (square == discriminant) && (candidate % 6 == 5);
}

bool pent_contains(vector* table, size_t function(size_t), size_t value){
	size_t result = vpeek(table);
	while (result < value){
		result = function(table->length);
		vpush(table, result);
	}
	void* pointer = bsearch(&value, table->data, table->length, sizeof(size_t), cmp_size_t);
	return pointer != NULL;
}

size_t pent_get(vector* table, size_t function(size_t), size_t target){
	for (size_t index = table->length; index <= target; index++){
		vpush(table, function(index));
	}
	return vget(table, target);
}

size_t closest_pair_closed_sum_difference( size_t function(size_t) ){
	// Let f: N_0 -> N_0 be an increasing function.
	// Find indices i, j such that f(i) ± f(j) are both in the image of f
	// such that D = |f(i) - f(j)| is minimal.
	// return D.
	vector* table = vnew(10);
	size_t j = 0;
	while (true){
		size_t self = pent_get(table, function, j);
		for (size_t i = 0; i < j; i++){
			size_t other = pent_get(table, function, i);
			if ( vcontains_sorted(table, self - other) && is_pentagonal(self + other) ){
				vfree(table);
				return self - other;
			}
		}
		j++;
	}
}

int main(){
	printf("%lu\n", closest_pair_closed_sum_difference(pentagonal));
	return 0;
}